# WatchRARr Configuration File
# Copyright (C) 2023 HomeLabineer
# """
# config.yaml - A Python configuration file for WatchRARr

# ------------------------------
# WatchRARr Info
# ------------------------------
# Copyright (C) 2023 HomeLabineer
# This project is licensed under the MIT License. See the LICENSE file for details.
# Script Name: watchrarr.py
# Description: A script to recursively watch a directory for RAR files and extract them upon creation.
#              The script processes both single RAR files and split/spanned RAR archives. It also maintains
#              a SQLite database to keep track of processed files and avoid reprocessing them.
# """

# The log file path
log_file: app/logs/watchrarr.log

# The maximum log file size in MB
max_log_size: 10

# The number of log files to keep in rotation
log_rotations: 9

# The scan interval in seconds (5 minutes = 300)
scan_interval: 600

# The SQLite database file path
db_file: /app/db/extracted-files.db

# The logging level (DEBUG, INFO, WARNING, ERROR, or CRITICAL)
logging_level: 'INFO'

# If running in docker:
watch_directory: /app/watch
# and in your docker-compose, you will need:
# /<your-local-path>:/app/watch_directory

# if running as a script:
# <your-local-path>/watch/

