# watchrarr.py configuration file
# Copyright (C) 2023 HomeLabineer
# This project is licensed under the MIT License. See the LICENSE file for details.

# Path to the directory you want to watch.
path: test

# Use polling observer (useful for NFS shares). Set to 'true' or 'false'.
polling: true

# Polling interval in seconds. Must be a positive number greater than 0 and less than or equal to 300.
interval: 5

# Path to the log file where events will be recorded.
log_file: watchrarr.log

# Enable debug logging. Set to 'true' or 'false'.
debug: false

# The maximum size of the log file in MB before it's rotated. Must be an integer between 10 MB and 100 MB.
max_log_size: 10

# The number of backup log files to keep before overwriting the oldest log file. Must be an integer between 1 and 100.
log_backup_count: 9
