"""
docker-compose.yaml - A Docker-compose configuration file for WatchRARr

------------------------------
WatchRARr Info
------------------------------
Copyright (C) 2023 HomeLabineer
This project is licensed under the MIT License. See the LICENSE file for details.
Script Name: watchrarr.py
Description: A script to recursively watch a directory for RAR files and extract them upon creation.
             The script processes both single RAR files and split/spanned RAR archives. It also maintains
             a SQLite database to keep track of processed files and avoid reprocessing them.
"""

services:
  watchrarr:
    image: homelabineer/watchrarr:latest
    container_name: watchrarr
    restart: unless-stopped
    volumes:
      - /<your-local-path>/watchrarr/config.yaml:/app/config.yaml
      - /<your-local-path>/watchrarr/logs:/app/logs
      - /<your-local-path>/watchrarr/db:/app/db
      - /<your-local-path>:/app/watch
